### ISSUE TITLE
基于原版docker镜像重制的新镜像，适用于多平台

### ISSUE THREAD

**Issue by nevinen** [MoeNetwork/Tieba-Cloud-Sign#117]
## 说明

我基于原版docker镜像的Dockerfile重制了一个新的镜像，同时对逻辑也作了一定调整，适用于多平台，以满足没有amd64架构机子的人使用，同时还以一些其他不同之处：

- 减小约一半体积；
- 多平台可用，`linux/386`, `linux/amd64`, `linux/arm64`, `linux/arm/v7`, `linux/arm/v6`, `linux/s390x`；
- 基于`alpine3.14`及其最新版本的`php`, `caddy`等；
- 降低POST上限为128M，降低文件上传许可为128M；

## 链接

- 镜像：https://hub.docker.com/r/nevinee/tieba-cloud-sign
- Dockerfile：https://github.com/nevinen/dockerfiles/tree/master/tieba-cloud-sign

## 创建

`docker-compose.yml`文件如下，**除了镜像名称不同外，其余同 [官方教程](https://github.com/MoeNetwork/Tieba-Cloud-Sign) 一致。**

创建好后访问`http://<ip>:8080`进行下一步操作。

```
version: "2.0"
services:
  web:
    image: nevinee/tieba-cloud-sign  # 本镜像名称
    container_name: tieba
    restart: always
    hostname: tieba
    environment:
      DB_HOST: db:3306
      DB_USER: root
      DB_PASSWD: janejane123456
      DB_NAME: tiebacloud
      CSRF: "true"
    ports:
      - 8080:8080
    links:
      - db
    depends_on:
      - db

  db:
    image: mysql:5
    container_name: db
    restart: always
    hostname: db
    environment:
      MYSQL_DATABASE: tiebacloud
      MYSQL_ROOT_PASSWORD: janejane123456
    volumes:
      - ./mysql:/var/lib/mysql
```
