### ISSUE TITLE
最新版本的docker镜像账号绑定php加载缓慢，且刷新贴吧列表为空

### ISSUE THREAD

**Issue by Mrkelo** [MoeNetwork/Tieba-Cloud-Sign#227]
- [ √] 我已升级贴吧云签到到最新版本，并且运行了升级脚本
- 直接使用最新docker镜像进行部署
- [ √ ] 我已搜索过 Issue 区，没有找到相关问题

问题1：
使用docker-compose部署镜像后
进行账号绑定操作时，php运行耗时超过100秒
![image](https://user-images.githubusercontent.com/34513356/208248186-c4f5a810-d939-43f7-9722-966314cb98ab.png)

问题2：
根据其他issus中反馈，使用.tieba.baidu.com中的STOKEN
和.baidu.com中的BDUSS
依旧无法正常获取贴吧列表
![image](https://user-images.githubusercontent.com/34513356/208248256-e2071044-5538-4c45-b2f2-9c240ebe3d2e.png)
问题3：
扫码绑定不可用
![image](https://user-images.githubusercontent.com/34513356/208248353-40a034fd-72d0-4a0c-90d9-1178bb8c43af.png)

# 复现步骤
1、使用code中指引，采用docker-compose进行部署
首次启动Tieba-Cloud-Sign无法正常运行，需要重启之后才能正常进入安装界面
按照安装指引一直下一步完成配置进入绑定界面
等待100s之后进入百度账号管理，开始绑定百度账号
使用.tieba.baidu.com中的STOKEN和.baidu.com中的BDUSS进行绑定操作
进入云签到设置，刷新列表后依旧为空

# 环境

 - 云签到版本：V5.0
 - 服务器系统和版本：底层debian10 部署docker V20.10.22
 - 云签到是否在 Docker 中运行：是
 - PHP 版本：8.0.22
 - MySQL 版本：10.6.11-MariaDB-log

**Comment by BANKA2017** [comment]
我猜是dns的问题，可能需要修改 `/etc/hosts` 解决

在 `docker-compose.yml` 的web节点（如下）里面加一项 https://github.com/MoeNetwork/Tieba-Cloud-Sign/blob/17518f5c727c5790bca5b23f4ca5fd7e7517b742/docker/docker-compose.yml#L3-L21

```yaml
extra_hosts:
  tieba.baidu.com: "183.232.231.118"
  c.tieba.baidu.com: "39.156.66.138"
  zhidao.baidu.com: "112.34.111.123"
  wenku.baidu.com: "183.232.232.77"
  passport.baidu.com: "183.232.232.87"
```

我这个示例仅供参考不过确实是可以用的，修改好以后停止并且删掉现有的容器，将以下这行的 `# ` （注意井号后面还有个空格）删掉

https://github.com/MoeNetwork/Tieba-Cloud-Sign/blob/17518f5c727c5790bca5b23f4ca5fd7e7517b742/docker/docker-compose.yml#L13

重新执行 `docker-compose up -d` 或 `docker compose up -d`
