### ISSUE TITLE
20241222最新版本启动报错

### ISSUE THREAD

**Issue by 907739769** [MoeNetwork/Tieba-Cloud-Sign#277]
- [ ] 我已升级贴吧云签到到最新版本，并且运行了升级脚本
- [x] 我已搜索过 Issue 区，没有找到相关问题

# 问题描述

```log
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/10-fix-owner
[cont-init.d] 10-fix-owner: Change /var/www owner to user caddy...
[cont-init.d] 10-fix-owner: PUID=1026
[cont-init.d] 10-fix-owner: PGID=100
cont-init: info: /etc/cont-init.d/10-fix-owner exited 0
cont-init: info: running /etc/cont-init.d/20-fix-config
[cont-init.d] 20-fix-config: Modify /var/www/config.php to the value set by the user...
cont-init: info: /etc/cont-init.d/20-fix-config exited 0
cont-init: info: running /etc/cont-init.d/30-set-crontab
[cont-init.d] 30-set-crontab: Set crontab to system...
cont-init: info: /etc/cont-init.d/30-set-crontab exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun caddy (no readiness notification)
services-up: info: copying legacy longrun crond (no readiness notification)
services-up: info: copying legacy longrun php-fpm (no readiness notification)
s6-rc: info: service legacy-services successfully started
exec: fatal: unable to exec bash
: No such file or directory
exec: fatal: unable to exec bash
: No such file or directory
WRN ts=1734837969.8406398 msg=failed to set GOMAXPROCS error=open /sys/fs/cgroup/cpu/cpu.cfs_quota_us: no such file or directory
INF ts=1734837969.8447082 msg=using config from file file=/etc/caddy/Caddyfile
INF ts=1734837969.85734 msg=adapted config to JSON adapter=caddyfile
WRN ts=1734837969.8602486 msg=Caddyfile input is not formatted; run 'caddy fmt --overwrite' to fix inconsistencies adapter=caddyfile file=/etc/caddy/Caddyfile line=2
WRN ts=1734837969.862275 logger=admin msg=admin endpoint disabled
INF ts=1734837969.8669243 logger=http.log msg=server running name=srv0 protocols=["h1","h2","h3"]
ERR ts=1734837969.8878407 msg=unable to create folder for config autosave dir=/root/.config/caddy error=mkdir /root/.config: permission denied
INF ts=1734837969.887944 msg=serving initial configuration
WRN ts=1734837969.8880763 logger=tls msg=unable to get instance ID; storage clean stamps will be incomplete error=open /root/.local/share/caddy/instance.uuid: permission denied
ERR ts=1734837969.8883336 logger=tls msg=could not clean default/global storage error=unable to acquire storage_clean lock: creating lock file: open /root/.local/share/caddy/locks/storage_clean.lock: permission denied
INF ts=1734837969.8894024 logger=tls msg=finished cleaning storage units
INF ts=1734837969.86694 logger=tls.cache.maintenance msg=started background certificate maintenance cache=0xc0001bd300
exec: fatal: unable to exec bash
: No such file or directory
exec: fatal: unable to exec bash
: No such file or directory
```

# 复现步骤

最新版本配置，更新最新版本启动报错

# 环境
```yaml
version: "2.0"
services:
  web:
    image: moenetwork/tieba-cloud-sign
    restart: always
    environment:
      - PUID=1026  # 可修改为你想以什么用户运行caddy，该用户的UID
      - PGID=100  # 可修改为你想以什么用户运行caddy，该用户的UID
      - DB_HOST=db:3306
      - DB_USER=tiebacloud
      - DB_PASSWD=janxxx6  # 数据库密码
      - DB_NAME=tiebacloud        # 数据库名
      - CSRF=true
      - TC_AUTO_CREATE_INSTALL_LOCK=true # 如果希望自动创建install.lock请解除此注释
    volumes:                                        # 如果重新创建或更新镜像希望保留之前的所有信息，请解除此两行注释
      - ./install.lock:/var/www/setup/install.lock  # 在当前目录下自行新建文件install.lock，内容为：1
    ports:
      - 38080:8080
    links:
      - db
    depends_on:
      - db

  db:
    image: linuxserver/mariadb:latest
    container_name: tieba_mariadb
    restart: always
    volumes:
      - ./mysql:/config
    environment:
      - MYSQL_ROOT_PASSWORD=janxxx6
      - MYSQL_DATABASE=tiebacloud
      - MYSQL_USER=tiebacloud
      - MYSQL_PASSWORD=janxxx6
      - PGID=100
      - PUID=1026
      - TZ=Asia/Shanghai
```
 - 云签到版本：
 - 服务器系统和版本：
 - 云签到是否在 Docker 中运行：是
 - PHP 版本：
 - MySQL 版本：
